[webapp] buttons in city ("Счета", "История счетов")
AshFungor/hope-project pull request #49
Opened 2024-06-19 18:07 UTC by LEgorisheA

2024-06-19 20:44 UTC, AshFungor approved these changes

2024-06-19 20:45 UTC, AshFungor requested changes

2024-06-19 20:45 UTC, AshFungor commented on app/routes/main.py
> -login_manager = LoginManager()
а зачем?

2024-06-19 20:56 UTC, LEgorisheA commented on app/routes/main.py
> -login_manager = LoginManager()
Что-то я сам не понял, как это произошло. Этого задумано не было.

2024-06-22 20:10 UTC, AshFungor approved these changes

2024-06-22 20:10 UTC, merged